### ISSUE TITLE
[0410] [확인부탁드립니다] 현재 Header Conflict관련 이슈

### ISSUE THREAD

**Issue by swing-park** [zel0rd/todo-list#16]
## 내용

Header부분을 같이 작업해서 컨플릭트가 납니다. 어떤걸 살릴 지 의논하고 머지해야 될 것 같습니다 !
Sienna가 스타일과 view작업 해주신다고 했으니 계속 해주시고 영이 올린 거 확인하셔서 병합해주시면 될 것 같습니다 !
저는 영이랑 오늘 만나니 논의하고 어떻게 작업진행할지 이슈 메이킹 해놓겠습니다.
일단 저는 이슈메이킹 해놓은 데이터베이스간의 통신과 View에서 이벤트 발생하면 데이터 베이스에 추가/삭제하는 기능을 개발하겠습니다~

## 멤버 확인

- [x] Swing
- [ ] Sienna
- [x] young

**Comment by swing-park** [comment]
확인하시고 issue close 부탁드립니다 !

**Comment by zel0rd** [comment]
conflict부분에서 필요없는 부분은 제거하였고 논의가 필요한 부분에 대해서만 주석처리해두었습니다. 

주석처리 부분만 월요일에 논의하면 될 것 같습니다. Issue 닫겠습니다.
