### ISSUE TITLE
[0410] header title부분 conflict해결로 인한 PR

### ISSUE THREAD

**Issue by zel0rd** [zel0rd/todo-list#17]
header title conflict를 처리하고 merge해두었습니다.
-> 필요한 부분은 월요일에 논의 후 처리하겠습니다.

확인하시고 pull 부탁드립니다.

- [x] young
- [x] swing
- [x] sienna

**Comment by swing-park** [comment]
확인 후 pull 땡겼습니다~

**Comment by Seohyoung** [comment]
closed
