### ISSUE TITLE
[PR] dev에 머지했습니다. 확인 후 마지막사람이 close해주세요.

### ISSUE THREAD

**Issue by swing-park** [zel0rd/todo-list#8]
## 내용
- mock data를 이용한 view를 구성했습니다. Dev에서 pull후 작업바랍니다.

## 멤버 확인

- [x] Swing
- [x] Sienna
- [x] young

**Comment by swing-park** [comment]
pull 완료

**Comment by Seohyoung** [comment]
pull 완료

**Comment by zel0rd** [comment]
확인완료!!
